#!/bin/bash

# Script to generate comprehensive documentation for all OpenCode tools
# Creates a markdown file with agents, skills, and commands details

set -e

# Define paths
OPENCODE_DIR=".opencode"
OUTPUT_FILE="docs/tools-reference.md"

# Function to extract frontmatter value
# Usage: extract_frontmatter "key" "file_path"
extract_frontmatter() {
    local key="$1"
    local file="$2"
    
    # Extract the value between --- delimiters, looking for the key
    awk -v key="$key" '
        BEGIN { in_frontmatter = 0 }
        /^---$/ { in_frontmatter = !in_frontmatter; next }
        in_frontmatter && $0 ~ "^" key ":" {
            # Extract value after the key
            sub("^" key ":[[:space:]]*", "")
            # Remove quotes if present
            gsub("\"", "")
            gsub(/^[[:space:]]+|[[:space:]]+$/, "")
            print
            exit
        }
    ' "$file"
}

echo "Generating OpenCode Tools Documentation..."

# Create the documentation header
cat > "$OUTPUT_FILE" << 'EOF'
# The Perfect OpenCode - Tools Reference

This document provides a comprehensive reference for all agents, skills, and commands available in The Perfect OpenCode. This file is automatically generated - do not edit manually.

---

## Table of Contents

- [Agents](#agents)
- [Skills](#skills)
- [Commands](#commands)

---

## Agents

Agents are specialized AI assistants designed for specific tasks in The Perfect OpenCode. Each agent has a unique personality, expertise, and set of tools tailored to their domain. You can invoke agents using the `@agent-name` syntax or switch between them using keyboard shortcuts.

The Perfect OpenCode provides several built-in agents that cover different aspects of software development. Each agent is configured with specific permissions and capabilities to excel in their domain while maintaining security and consistency.

| Name | Description | Model |
|------|-------------|-------|
EOF

# Process Agents
echo "Processing agents..."
for agent_file in "$OPENCODE_DIR"/agents/*.md; do
    if [ -f "$agent_file" ]; then
        name=$(basename "$agent_file" .md)
        description=$(extract_frontmatter "description" "$agent_file")
        model=$(extract_frontmatter "model" "$agent_file")
        
        # Use N/A if model is empty
        if [ -z "$model" ]; then
            model="Default"
        fi
        
        # Escape pipe characters in description
        description=$(echo "$description" | sed 's/|/\\|/g')
        
        echo "| \`$name\` | $description | \`$model\` |" >> "$OUTPUT_FILE"
    fi
done

# Add Skills section
cat >> "$OUTPUT_FILE" << 'EOF'

---

## Skills

Skills are reusable sets of instructions and workflows that provide domain-specific guidance. They can be loaded by agents to access specialized knowledge, templates, and best practices for particular technologies or frameworks. Skills follow a progressive disclosure pattern, providing essential information first with detailed references available on demand.

The Perfect OpenCode comes with a comprehensive collection of skills covering programming languages, frameworks, tools, and development workflows. Each skill provides targeted guidance and can include reference materials, examples, and helper scripts.

| Name | Description |
|------|-------------|
EOF

# Process Skills
echo "Processing skills..."
for skill_dir in "$OPENCODE_DIR"/skills/*/; do
    if [ -d "$skill_dir" ]; then
        skill_file="$skill_dir/SKILL.md"
        if [ -f "$skill_file" ]; then
            name=$(basename "$skill_dir")
            description=$(extract_frontmatter "description" "$skill_file")
            
            # Escape pipe characters in description
            description=$(echo "$description" | sed 's/|/\\|/g')
            
            echo "| \`$name\` | $description |" >> "$OUTPUT_FILE"
        fi
    fi
done

# Add Commands section
cat >> "$OUTPUT_FILE" << 'EOF'

---

## Commands

Commands are custom slash commands that provide quick access to common workflows and operations. They can be invoked using the `/command-name` syntax in the chat interface. Each command can specify which agent and model should be used to execute it, ensuring optimal performance for the task at hand.

The Perfect OpenCode includes several built-in commands that streamline common development tasks. Commands can combine multiple operations, provide interactive workflows, and leverage specialized agents for complex tasks.

| Name | Description | Agent | Model |
|------|-------------|-------|-------|
EOF

# Process Commands
echo "Processing commands..."
for command_file in "$OPENCODE_DIR"/commands/*.md; do
    if [ -f "$command_file" ]; then
        name=$(basename "$command_file" .md)
        description=$(extract_frontmatter "description" "$command_file")
        agent=$(extract_frontmatter "agent" "$command_file")
        model=$(extract_frontmatter "model" "$command_file")
        
        # Use N/A if agent or model is empty
        if [ -z "$agent" ]; then
            agent="Default"
        fi
        if [ -z "$model" ]; then
            model="Default"
        fi
        
        # Escape pipe characters in description
        description=$(echo "$description" | sed 's/|/\\|/g')
        
        echo "| \`/$name\` | $description | \`$agent\` | \`$model\` |" >> "$OUTPUT_FILE"
    fi
done

# Add footer
cat >> "$OUTPUT_FILE" << EOF

---

## How to Use

### Using Agents

- **Switch agents**: Use keyboard shortcuts or tab completion to switch between agents
- **Mention agents**: Use \`@agent-name\` to invoke a specific agent for a task
- **Learn more**: Check the agent configuration in \`.opencode/agents/\`

### Using Skills

- **Load skills**: Agents can automatically load relevant skills based on context
- **Manual loading**: Reference skills using \`@.opencode/skills/skill-name/\`
- **Explore skills**: Browse available skills in \`.opencode/skills/\`

### Using Commands

- **Run commands**: Type \`/command-name\` in the chat interface
- **Command arguments**: Some commands accept arguments: \`/command-name arg1 arg2\`
- **Custom commands**: Create your own commands in \`.opencode/commands/\`

---

**Generated on:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

**Repository:** [The Perfect OpenCode](https://github.com/the-perfect-developer/the-perfect-opencode)
EOF

echo "✓ Documentation generated successfully!"
echo "Output file: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  Agents: $(find "$OPENCODE_DIR/agents" -type f -name "*.md" | wc -l)"
echo "  Skills: $(find "$OPENCODE_DIR/skills" -type d -mindepth 1 -maxdepth 1 | wc -l)"
echo "  Commands: $(find "$OPENCODE_DIR/commands" -type f -name "*.md" | wc -l)"
